[package]
name = "mc_auto_fish"
version = "0.1.0"
authors = ["muumlover <muumlover@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3", features = ["winuser"] }
